AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB nested stack
Resources:
  DemoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: demo-table-cf
Outputs:
  TableName:
    Value: !Ref DemoTable
    Export:
      Name: !Sub "${AWS::StackName}-TableName"
