AWSTemplateFormatVersion: '2010-09-09'
Description: VPC nested stack for serverless demo
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: cf-vpc
        - Key: Team
          Value: networking-B

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
Outputs:
  VpcId:
    Value: !Ref VPC
  PublicSubnetIds:
    Value: !Ref PublicSubnet1

